export const TABLE_HEAD = [
  "",
  "Lite",
  "Basic",
  "Pro",
  "Ultra",
  "Premium",
  "Enterprise",
];
export const TABLE_BOTTOM = [
  {
    Label:'Features',
    active: false
  },
  {
    Url: "/Get-Started",
    Label: "Get Started",
    active: true
  },
  {
    Url: "/Get-Started",
    Label: "Get Started",
    active: true
  },
  {
    Url: "/Get-Started",
    Label: "Get Started",
    active: true
  },
  {
    Url: "/Get-Started",
    Label: "Get Started",
    active: true
  },
  {
    Url: "/Get-Started",
    Label: "Get Started",
    active: true
  },
  {
    Url: "/contact",
    Label: "Contact us",
    active: true
  },
];

export const CHECK_ICON = ["Yes", "No"];

export const PRICE_LIST_AMOUNT = [
  {
    Column1: "Monthly Price ($)",
    Lite: "$19",
    Basic: "$49",
    Pro: "$99",
    Ultra: "$199",
    Premium: "$499",
    Enterprise: "Custom",
  },
];
export const TOP_PRODUCT_PRICE_LIST = [
  {
    Column1: "Free Monthly Transactions",
    Lite: 200,
    Basic: 800,
    Pro: 1500,
    Ultra: 3000,
    Premium: 10000,
    Enterprise: "Custom",
  },
  {
    Column1: "Additional Transactions",
    Lite: "$0.20",
    Basic: "$0.15",
    Pro: "$0.15",
    Ultra: "$0.10",
    Premium: "$0.05",
    Enterprise: "Custom",
  },
  {
    Column1: "Number of Integrations",
    Lite: 2,
    Basic: 3,
    Pro: 4,
    Ultra: "Unlimited",
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
  {
    Column1: " Giftcard Program",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Store Credits",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Loyalty Program",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Coupons",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Referral Program",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "VIP Tiers",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Automation Workflows",
    Lite: "No",
    Basic: 1,
    Pro: 5,
    Ultra: 10,
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
  {
    Column1: "Stores (Including physical stores)",
    Lite: "No",
    Basic: "No",
    Pro: "3 stores",
    Ultra: "5",
    Premium: "10",
    Enterprise: "Custom",
  },
  {
    Column1: "Heartland Retail",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Lightspeed X-Series",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Lightspeed R-Series",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Lightspeed K-Series",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Lightspeed O-Series",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Square POS",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Runit POS",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Connect POS",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Clover POS",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Salesforce Integration",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  {
    Column1: "Microsoft Dynamic 365",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  {
    Column1: "Shopify Flows Integration",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Shopify Checkout Extensions",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Shopify POS Extensions",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Shopify Account Extensions",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Shopify Metafields",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Apple Pass & Google Wallet Integration",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Loyalty Page & Dashboard",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
];

export const REMAINING_PRODUCT_PRICE_LIST = [
  {
    Column1: "Number of Campaigns",
    Lite: 3,
    Basic: 5,
    Pro: 15,
    Ultra: 40,
    Premium: 100,
    Enterprise: "Custom",
  },
  {
    Column1: "Import Giftcards",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Gift Card Widget Customization",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Resend Emails",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Custom Gift Card Artworks",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Expiring Store Credits",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Check Balance Page",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Workflow Delay Action",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Time-Sensitive Workflow Conditions",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Workflow Cart Item Filters",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Print at Home",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },

  {
    Column1: "Giftcard Discounts & Promotions",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Schedule Gift Card Delivery",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Default Email Customization",
    Lite: "Yes",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Reports",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Custom Email Templates",
    Free: "No",
    Lite: "No",
    Basic: 3,
    Pro: 10,
    Ultra: 20,
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
  {
    Column1: "Barcode Generation",
    Free: "No",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Bulk Giftcard Creation",
    Free: "No",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Web POS",
    Free: "No",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Physical Gift Card Support",
    Free: "No",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Multi Currency Support",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Remove Branding",
    Free: "No",
    Lite: "No",
    Basic: "Yes",
    Pro: "Yes",
    Ultra: "Yes",
    Premium: "Yes",
    Enterprise: "Yes",
  },
  {
    Column1: "Team Management",
    Free: "No",
    Lite: "No",
    Basic: 5,
    Pro: 10,
    Ultra: 25,
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
  {
    Column1: "B2B Distribution",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  {
    Column1: "Two Factor Authentication",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  {
    Column1: "API Access",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  {
    Column1: "Custom 3rd Party POS Support",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  {
    Column1: "Account Manager",
    Free: "No",
    Lite: "No",
    Basic: "No",
    Pro: "No",
    Ultra: "No",
    Premium: "No",
    Enterprise: "Yes",
  },
  // {
  //   Column1: "Infrastructure",
  //   Free: "Shared",
  //   Lite: "Shared",
  //   Basic: "Shared",
  //   Pro: "Shared",
  //   Ultra: "Shared",
  //   Premium: "Shared",
  //   Enterprise: "Shared or Dedicated",
  // },
];
